### ISSUE TITLE
Blank White MiniPlayer

### ISSUE THREAD

**Issue by Thrashers** [eltoncezar/Spofy#20] opened 2018-04-15 04:50 UTC
I've tried to get this to work but the miniplayer only ever shows a blank white box for me. Is there something I'm doing wrong here?

**Comment by eltoncezar** [comment] 2018-06-08 00:19
Fixed in 2b103fd0d3fe0ee369567cbd21a3bcff6dd4de61. Sorry for the late reply.

**Closed as completed** 2018-06-08 00:19 UTC
Labels: bug

**Comment by eltoncezar** [comment] 2018-06-08 00:29
Duplicate of #17
